apiVersion: v2
name: nextlinux-engine
version: 1.15.0
appVersion: 1.0.0
description: Nextlinux container analysis and policy evaluation engine service
keywords:
 - analysis
 - docker
 - nextlinux
 - "nextlinux-engine"
 - image
 - security
 - vulnerability
 - scanner
home: https://nextlinux.com
sources:
 - https://github.com/nextlinux/nextlinux-engine
maintainers:
 - name: zhill
   email: zach@nextlinux.com
 - name: btodhunter
   email: bradyt@nextlinux.com
engine: gotpl
icon: https://nextlinux.com/wp-content/uploads/2016/08/nextlinux.png
dependencies:
 - name: postgresql
   version: "1.0.1"
   repository: "file://./deps/postgresql"
   condition: postgresql.enabled
 - name: postgresql
   version: "1.0.1"
   repository: "file://./deps/postgresql"
   condition: nextlinux-feeds-db.enabled,nextlinuxEnterpriseGlobal.enabled
   alias: nextlinux-feeds-db
 - name: postgresql
   version: "1.0.1"
   repository: "file://./deps/postgresql"
   condition: nextlinux-feeds-gem-db.enabled,nextlinuxEnterpriseFeeds.gemDriverEnabled
   alias: nextlinux-feeds-gem-db
 - name: redis
   version: "10"
   repository: "https://charts.bitnami.com/bitnami"
   condition: nextlinux-ui-redis.enabled,nextlinuxEnterpriseGlobal.enabled
   alias: nextlinux-ui-redis
