apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "charts.nextlinux.io/v1alpha1",
          "kind": "NextlinuxEngine",
          "metadata": {
            "name": "nextlinuxengine-sample"
          },
          "spec": {
            "nextlinuxGlobal": {
              "defaultAdminEmail": "example@email.com"
            },
            "postgresql": {
              "extraEnv": [
                {
                  "name": "POSTGRESQL_USER",
                  "value": "nextlinuxengine"
                },
                {
                  "name": "POSTGRESQL_PASSWORD",
                  "value": "nextlinux-postgres,123"
                },
                {
                  "name": "POSTGRESQL_DATABASE",
                  "value": "nextlinux"
                },
                {
                  "name": "PGUSER",
                  "value": "postgres"
                }
              ],
              "postgresDatabase": "nextlinux",
              "postgresPassword": "nextlinux-postgres,123",
              "postgresUser": "nextlinuxengine"
            }
          }
        }
      ]
    capabilities: Basic Install
    categories: Security
    certified: "true"
    containerImage: registry.connect.redhat.com/nextlinux/engine-operator:v1.0.0
    createdAt: "2021-08-12T04:55:44Z"
    description: Nextlinux Engine - container image scanning service for policy-based
      security, best-practice and compliance enforcement.
    operators.operatorframework.io/builder: operator-sdk-v1.9.0
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
    repository: https://github.com/nextlinux/engine-operator
    support: nextlinux.slack.com
  name: nextlinux-engine.v1.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Deploys Nextlinux Engine
      displayName: Nextlinux Engine Operator
      kind: NextlinuxEngine
      name: nextlinuxengines.charts.nextlinux.io
      version: v1alpha1
  description: "Nextlinux Engine is an open source software system that provides a centralized
    service for analyzing container images, \n scanning for security vulnerabilities,
    and enforcing deployment policies. Nextlinux Engine is provided as a Docker \n container
    image that can be run standalone or with an orchestration platform such as Kubernetes.
    Nextlinux Engine allows \n users to perform detailed analysis on their container
    images, run queries, produce reports, and define policies that \n can be used
    in CI/CD pipelines. Users can extend Nextlinux Engine with plugins that add new
    queries, image analysis, and \n policies. Nextlinux Engine can be accessed directly
    through a RESTful API or via the Nextlinux CLI.\n\n The Nextlinux Engine Operator
    is based on the official stable [Helm Chart](https://github.com/nextlinux/nextlinux-charts/tree/master/stable/nextlinux-engine)."
  displayName: Nextlinux Engine Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAkEAAACXCAYAAAAS/I+2AAAACXBIWXMAACxKAAAsSgF3enRNAAAaZklEQVR42u2d73EaTRLGH6v0HSVAwUUgiEDrCMxFIByBcQQeR2AcgVEEL4rghQiACA6KBCAC3YftldYISctOz7/d51dF3dWdDEvT0/1MT8/Mp6enJxBCyClDs78BMFiZ7oLWIIQ0kU8UQYSQkugZy+v2zJ8sAcxXpjultQghFEGEkKYIoAGAOYBehT/fABivTHdNyxFCKIIIISkLoBsAWwCdC/7ZDvlS2YEWJISkyhVNQEjrmVwogIC8YjSm6QghFEGEkJQZef53hBBCEUQIiYJbmoAQQhFECCGEEEIRRAghhBBCEUQIIYQQQhFECCGEEEIRRAghhBBCEUQIIYQQQhFECCGEEEIRRAghhBBCEUQIIYQQQhFECCGEEEIRRAghhBBCEUQIIYQQQhFECCGEEEIRRAghhBBCEUQIIYQQQhFECCGEEEIRRAghhBBCEUQIIYQQQhFECCGEEIogQgghhBCKIEIIIYQQiiBCCCGEEIogQgghhBCKIEIIIYQQiiBCCCGEEIogQgghhBCKIEIIIYQQiiBCCCGEEIogQgghhBCKIEIIIYQQiiBCCCGEEIogQgghhBCKIEIIIYQQiiBCCCGEEIogQgghhBCKIEIIIYQQiiBCCCGEkLNch/rgodn3AZRfb7GV12Flumv+ZB/aNZP/OgBw886fLgBgZboLWq2SXQt7fuSvawAHAOuV6R5oucr+mn3wp/TXy+x6IzHgI9sexGdp28tz13u2bW3eusD3orDTp6enJ19Ok4lhBgDuLN5uJ4N2AWDRZmEkCaRs117Ntzqe2LTVwVAET9mutwp2XYttDxF+37pBYLky3ayGvxa27dBf1WOBrW2L+LqmbVVjwUaSfaPylnJuD2InZyJIjDMCMLZwnKoBcQ5gvjLdeQsG5VjsmlkEuio8lux6aIFdM/HVzEJMJmlXVyJIZoQjeX1x/DXa5q++bNuq+Cq2HZVibI92PSsMizzUc/xxzu2kLoIkSY8VFKGNwczKdLcNGpR9AEacrhPIptOmVd0kkUzEX3sBHuEBwCz0bFtbBEmQnATy12js6lis3zO+qsfYcaBYEH2MlVg5lnHdC/QYTuykJoJE/JiABnoVoGWwLhIemJnY9I42dSIq7yN5pI0M7FnKIoj+yljAWNAsu5YmipNAExrndrIWQTI4ZxGJn1MeAUxSmrnIwJxFFPDOOeAktcqQDGgD4FvEdvUeAG1FkFR+pvTXVoif5OPrSXL/QZ9900YT8b1OxD+ltZ1qiyBxohncr/Vr8XNluiaBwWkiHpin/JakfUjAriPx104Cdn2QgX3wZJu6ImiDvIHxG/21dYI9yfiayMQ9qM/KpGYGt7280diplghKLKGcBu1xjDPCRB0PyHeTjCJfy05JrBccxVfnHmz0hPawE7sumKTbE19Ltp0mJCy921WqP7/aNLYvFkGJOlGQ5HKBTcfIlxM6Cdv1+8p0pxEKy3mCyeSvGc7KdCcUQc331wYkoSK+TkL1t30wGVokOMn0YlexzxTx9EbZcFFVsrIISnhGHXUQbICoLPOwMt0xhaU6S+TVtoMjW7VRBEXlr/I7zBqShC5ORB4mQ7OEBZBTuzZAIFqN7UoiqKFGCh4EGxb0okksIoD+NMyuGwCZCyHUYhEE5I2945B9QhJf54i3+TnlWDCQ3NWhXVuV2ytPHq9abqR7ESIUQA2waYMFEGT8LWQ8Ej2+iAAJyaKBAiiGWNBvoAAq7DpRsE+TcztkTC0++qOrigO0qUZScygKoPDBr8ECiELIcbAMPBlqenydBrBrUV3rNNSuv2SDkg3ThvseANx+NLbfXQ7zlKw3yC/xO6fYspKic81/Pe3E8ZWod8jvYDlHH36ahb31BXgsexf3VoW062ZlugNF28WwHNYqfxW7++oHfM+2A/gRCl99NksPzX4OP/2rb9nWh12PAAZ1zmjy1IBfxMrDmZhZvmT1LuTYflMEOTTSEXmT2uIS0VG6yG7sSL3WdqgLv8PKoZic44JLD0uXLo4czgg+u96OLLO+taNEuSvsiooXoHqyq2ZfQAgRVNdfB3B7H6GvydAIwD8ObTsDsI4sFgwbsM17KX77oW0lLpXt6iI+XXSJseM89HzPl9hne+EzFbZyJV7P5qKzIsiRkZbI7/OZKTh5Hy93PnVCOlTgRF0IyqmteCvdnaN9PPoRQN9l46mjWZ/K/VMOfVUtYXsUQfTXl1iwdfDcU/HZbaQ+66y533Hu2onfWtnW4b1vF000h2a/Vha6SxnTc8XxMYL+NVxnx/ZbIkjTSDvk5xvMHQUTA92SspOt8w5K305OEnV0nPzjynRHcICDGfUS+W6hbQJ2VUnYnkQQ/dWNaC/Ez9SRbbXjq9Nzr4Zmv4De8spR7GqUn7EP3WuRKi/jKrdjbCS3Lxz+nmNlMfTK/16JIOVSopfj/5XPgVCfCSrPTrycHurgbA31ZTHl6pqXQzQlAM4V7WqdsB2LIC8nijuwq5NlXGXRvhHbbj3EAs1DR//j4pmVE7yTydAZX5jBvtpWSQQpVyB9988ZxYnOX/539Yby1+DrynS9nL8hATYT0WVLR2ZWmmi93yPycvLah02l+fYhMhuUmSgF5qJMP/dg163Y9bfSW36RMnuMPCLvs1t7tKuWv84cParWOHhYme7Ax8Wl8vsN5PeM2bZauev3ynQz17aVeDOQ+OMDjaXjI/JleOMzkMjnfZbPV/W/K0dG+uz72PSV6R6kUVQjCN7LzFJDwWbQKXs+rEx35PtQN0Wb3spMTWtmUCyDaAmgtWe7TgB8jSz4a5K6v/Y0/bVUqegp2Xbs2a4HqThq2PZOW7gr2var62tqTsW7TOBthNCi4t/Z+szR12TxDVstxFZHBf/rvxJBikkl6OWEikFQK8hoJKigJ68q2lQzWWsIdueNmh/YdaYkhO4iqwbRX5sdCx4batvvIe48k/hTVwgtq+RbJZEY/HLc0qrPUctfypWgkUJS+R7DxaRKA1XjRM4B7KtAGyVxqmHTpcLsWitZa8xqgl6XoCyEDOKA/no+FmhskV5GctfZGPZLOHeK1XaNBP8Q8i7JmkLoeEEctG30/x3LpeMihGy/z+icCLINXI+R3co8tlSLHYUTOTUS9Sh0oj5xnGNgm2gllEnoWc2JELKtXKglFYXZYpP8VUvQqcSCSPz1AJ1K+UTxd7ZhF4lwv0QIFVXsbYV4eQO73Yg7n0uEFW21gF1f5XN+vxIj9WG3q+IIveWjmAZqaBE09dH4eKFNbQfDvcK1D7Z2XYYoe1dICLtIkkpdfsYiLBX99YutvyokoUK0HyKy7RrAz8DxVcu20Qj3khB6r4r5G5f1Mdra2SBOjOUkJ3sWQciPpbdN1ofYLCTlu2WIQSpldJvlxZ3vDvwLqha2pfDMNjEFFlGxJuyQlYKY/XUZ2K62/z5G0Q7kO91shHtPWgZC2vYhZA/rW7FADu39LIJniby94zvy7d2XCuKR5biO0feKmGmz+vSXCLLhCDfbnzXVYl06FoO0qepb49lsxKVG0NtGOqhtRXsv4JJYk/01C+XvMdtWkpAJbJvGxtmV6S5E8GSy07LuykDW0HEN2B23cFsWQWvULytFWQUqO5LlbCXz/O8A4Bir+i4l6xA21UhI08gHdeikUnciNG9wDLC1qY3P7mKrVJwwh8KShAU2VeHHWCdEWsikqGP5+yLisb2FxcrE0Oyzq5Kir5scZgn4gs0POahh2BvY9VilYFMbMWFTsbApn29i6llxlLAHAR57FvNESMFfO3X9VSrJnUDP7cNfD5bxtfbuWYWdeynEWVv6Fv92mcC4thZqVyVnNrh8h8pDIkp65tmJBi0YnLYzhLo2umu4XW1t209sfDXdXweBnzv6399CzNjY9hjLlm/H2AjFRSLf0UaDZFcnqn6MvOO/SnkzivNAKs5WbGb/dwEG5zoBm25h1yBdp8Jmm1BSGdQpBWf6qztRuklhkinVS5slsb7n3ySlWGDLTQtsZDVGrs44tBGn/P5O0HhAwJN2a7L0+Fn9lgxOm2cdeB7QSSTrUlKpyzohH2i6v7ZlJm77rH3P/65NIshGKG7bYKDrN4Jw0SM0lRl4phSgQ1JbsA3N/uZCwdeWGYpNwq0jaLJAzxqCR1ze9Blip2ZKdl0A+BZgRt2WWFC3STnEUmNq8SDEZKy9Ikh5ZtqUQbrw+JypYDNI+p6fNTUfnl7or8Xlhlva1Ym/huhhSykJLQD88CwwazecNySnueTYli96xd/aCTYJPpnAZxlIerTrh7b9b8VgtAQwCLTcl5K/2tink9jz+sZra4TlKd47tIe6Ijwl37Na8rsGcUHte63aUoKkuKzkC3PZmj2S183J91kDmIf0mQT99RhC0DR9Jr4y3fXQ7H0mava6EIogEgVL2JX8yfvJ5YB8C/KM1lBhnYi/smeFkGpkFv/2wOWwioby9Dk7mjr535AQEjdbmqAZyKYtm5WXNUVQRUNxcPI3JK/Y0ASEIogExNjGL4ogQkhdWF0jhARhaPYT2C1tr9smgvp0G0IIISR5ATQC8MvybeatEUFy3cI9XYcQQgj5kGirvFIB+sfybZ7vjmv87jBpnJrTpwkhhJBKRNdDKceFzKCzu/NZEzRWBEm5bAJu3yaEEEJSzeUZgDF0V3NM40SQLHllpVeH7kMIIYQkm88nsNgC/wYP5UNerxM2Uv9E9PToOoQQQgjz+RsccbKt/johI92IcUYUPYQQQkiyoufmRPTcevroyelVP9c0EiGEEEIc5/RyPg/Rq/uwMt3Z6f94TSMRQgghRDmf9/GycpMhbJ/uw8p0x+f+j+vARio3M3+h2xBCCCFJip6bE9ETS8vKmwLIuwiKTBkSQggh5DWVzgmSo2iKfB5jy8r3lelO3/sDpyLopNIzAJuZCSGEEOdIe0ldDu/k9EL4xNyysgMwXpnu4qM/vHZg+BG4g4sQQghJXUgVS1wjpNOy8hPAdGW6la7+uFYy1KhkKC5xEUIIIenSH5r9DGndufkAwJxugXcmgkQhTpAfZ93kis+R44EQQkiL+JNQfp4CmF0qfmqLoJL4mSCdqs8S+RpnnXLemuOBEEIIiYZHAPNz5/44E0EJip8NgAXytcHt0OwNuA2fEEIISVb4iPg5aL1pJREkXeYzxL3stRMDLQAszhhpQB8ihBBCkqAoZMyr7PJyJoKkgvIjQgMdCwOJ6Nl+8Pc39ClCCCGkvaKnsgiS5a8p4uoOX5ZED3t1CCGEkLRFzwLnV2/CiSARQAuEPwEyiDIkhBBCiCq7E9GzjeGh3qoEzQIJoMJI85DKkBBCCCFWXNqyEocI8ryL6lhShvNYjUQIIYSQyvk8mZaV6xMBlMF9E/RjakYihBBCyCuWpXy+SPELnFaCpo7U4UyMNKfPEEIIIUnSuD7dZxE0NPsxdPuAlsgPKoxF+HCLPCGEEHJ5Lp9B+ZDC6EQQAKNosEmES1239GVCCCGkEkcAo6bvzL4GgKHZD2B/GvRRxM+MvkNiY2j2A/agEUJI5Xzeb8MO7aISNFYwWMYkQyKGy6GE/krahM1VUZO2HFFTiKCR5fuMKIBayxbAHc3ghqHZ92V8jgD0kVdsNwAOeGlQDDX2eI6XO24T81Mb0bbjzx2dkN62xUhX4rw2S2G/eZpzqzEeP8sm2fcTFEBj+c6/RGj2SgnyDvlxFquh2S9kSds3U7o/Uag6bGk+EkwEWTrv0XMSJJEhB1w+ePo4m8pDUiJoaPYjAH8AdCr8+Z2IobHHR1xy8lOJnYUPZAl9zz5/apKqCLIZaPMWrBsy0H9MCkI4a4FN/8jyGX/zeNha/NtBQt+TlSCSrAiiQCBWSDXod+SCdJCYWev2hPgQJ4+sAlEEKU4yKIJIUBFk47xJBELLpj1SPfm6bnC0qTp2AvXN1PFXmzHZd/x4R9jvJqUIqsYoEX+9gV0jNzfVkKAiyLYCkAID/tRukWXRsePPsA2Wo0TMGfNzjtuydVYJm4liKsLd1l8pgkiaIoiQE5GyAPDd8ccsbRJ4C0SQy4nJb97/5z3BTxL4jjbj6pjQZJo0kOuWfE9WgvwJoanMXu8dzqzrnkvUG5p9FnM/i+zw6lnaxwWPK9Od0MMvHg+HodlvUH+5aDQ0+5tYq2/SiH8Xob8SOwGepfTbyJKskQlk72TSvEZ+j+lZsd2WSlCfg9Rr4B/D3bZ529/DNHhW7cpfN2AfUKjfpIO4q0G244mVRXe04kgRmXRvAXw7M4G8k//9f3KeWr+tIoiVoIYIIaniHC3e4i7W81ekCmQzq944WFrYIL8Sh31A9ZlZ/vtJjJs7lCq+FEHusIkFWWLjq+p5auvT89SubAyV0GFetRMLtwLHJ4QUAqeJzVaS5KYKwUCThwYKoEOAcbCG3c7JDuI8ndv2mR4prp36nY0I6nk8c8x24nh76VgqbziwEkFIoMIiJ+/WxfedNvMGDsQxgK+R2eluaPaxLTFUnc348p+fK9Nt4k6wecDf14Z7y1imHVcnsL8zcN4yHwhB0zeS1HnGv5aYbUVQloCRbALHwuNzHh3M5GMRQjMAQ+RLKxrvN1cQqL9i2X48NHsD4IvCrHqr8Dg7AJ9Xpmsa7IshLuzUGNuzGHxWnuGXbbyT38K7KGjZZd823zVqEWTZlD8qiyAbI32JuWQmSwz3gRzoUqZNLg2vTHe9Mt0BgJ+w6+l5tpfCeyxC+6+Uc39EYo+fAAYtWAKeBfD/LeyXhjsihG4C+utAaXIYannPoF3Y/FY9z/cR+vwtn6vuV6KKjw11KtslD19l0yNaciO3VBgGCglhpiCmOgDmoYSQLCn8UZrd2gS7BwD/WZmuaUmPxhRhqkEasfI2lHgvCSDbZdtQ8a6Nl/7afl8TaVN+ZlngeM4dVwrJ/j7GU00lSNiIoJ3HQ7ymbWoQXJnuVnqFbN7joBRIb5HvGBh49M2bodnPYL+koJJcpfdn2yL/O4SYvClVg8o+m3n02bGSAAoZ7wxahtj50eItepHazTb2zzVFUDErj9FInQS+066p/RceBrhRmtF3AKx8NEtL4lpD7zDJ39zBWMt3ZrBrGq3LBDrLwR0A/w7Nfupypi6CfY68YqkhgELFu4cWjxPbXPYtpp3gQ7Ofwu6uur9E1JUEhLnlwLyVmW0sRprAvtHU1/cZgdgwVnyvX0OzdzLDHpp9X8bIv7A7EbrMsY2zW2XfOfr8QAdVqG84c/aJkvgxyDfOfIl0vF4yTlp72rnSRpJ5JE35Y/F5G/5qjr9STPr3MQghMZLtMsOjp+WBny3bqeBigC8A/FZ8y1uZYS80EsvQ7DMZF/+D/lUiI56zYuU72xDJcWW6U9gtUZzSA/BnaPYHqQwNFPx1i7xhv6P4nKGqlhwn9vm9g7wXLZgQknis0UP51yTk09PT0/NMVQK1LQ+2/R4RGOmzzWAdmv1TRaHFKpDSrBV5v8Ktg7c/ynvPAaw/Eq0yjgbIK3wZ9Ko+5wS04a+v4j+zKgJ1ZbqflH127dA/dvL+a7w0x26LyZ0ksxt5DeSVKYueMhvZHaplvwx5VfUjvovoZIzMha1GU3vme/KumNuXK9PNzoog+aAp7EtNgNw15NNQis/+ykgORBCvItD//bV2rlQNBKe+feNIhEU10Wiw/8zxwbKPpggK4LMhOQLoa8a7iiKI4+Rvm02gtxnDi7gsnaSvVUV/VeA4vTvMQGeN/BZ5o6nz7XVSvl0rCaDCBi6hAHKACO7M08d1kB/SVX75EkAbtLi/wSFjKB3meaHPNj1JHwPFOwqg1/42VfTxX9Iy4CzmygnpmptIzjbHX50YSbtp7weArYihvgPxs5DZwK1LI1EAJSWEvjb4K9J/3PnOQUT0o+fPnTfYZ4MsnVAAvYvmBOoOef/kXFMMlXL7P9DdRHL2u/+1HFZ6iA9LwzV5hPRX1Gk8FkOP5NVzMGBVSrZvLIc9AJgwgblHcf2YAqid/nN2aV17OeyMz9oe69EaAfTOchh7gD62nYHOKfWn7JA3YM8v/d1laTgToeKiT+7NPt+3RJDrpr1ikBSNewd5lQ1XKMu+vO4c+8ZnrSrQ0OwPJ8GMA9P/QG9SvwVntmGE9F+ixKUIapjPOu8JPbOR54h8F9iC3lvJfgvHOfU0vxf/eZrfM+RN+S59/t1NJGdFUAOTiJWRLBxsibz6w23wYQZ6H/murtuEvwYFdFj/mclYVt3d9M5n3ojP3iVqtkcRQAcPtiqSF6vs9fxskXhsVJlAvimCxFAZqm1D5Cz79SwSgW5JJq8Hu4Fe47wvdjKzpYAO70Mj5BfLGo+faeBmycLlzH/iM+aJjRas/tS2X9MLHZV2er8rgkoJfdpQQ3GZoT0DPpNZfS+Bx/2Jlt0nR876bB8vlaio4yhYiaEQikwAoeIhmR+KoAYbigKonYPeIG++60Q6cFt1mSmp5LMjmYj2IvRXw0pMI4TQDM1ZGrsot1cSQQ00FAVQuwf9jQihWMQQkwmp4rdj5OcKha4MPSKvVNJfmxUTU+5FK7i4v7eyCCoZSvP0Rt94X7cm0Q/8kYih2wC+OBfxs+WvQS6cuReCyJeIL7Y/z+ivjfYtg7R60crxdCznbl3ERSKoZKiRDIiUlse8X+VBkhr8fRFEY4eCqBA+8zqDlZAzfpvh5Z46bb9d4uVcN8bNdvnUDGn0TwKWOxJriaDSLHqSgGo8Ii/dGro3ucC3M7ycYVH3HIsN8ksLF8h3sTCRENd+Wxw61y+9ehX8tDjLZYv8ouAFLdp6fzKIt38SyKuTE9sJZW0RdDKDNohvieyIfOmOu2yI5gwJeLl5+5QicWy5ZEAIaYiwjql/shA/RqutxVoEnYihsbx6gQ00o/ghhBBCVMVQyPy+kbw+03xTNRF0YrDifq+RJ/XIXgtCCCHEvSDymd93kttnrtoJnIigE4MNxFjFWrWG0Yp7SRbgiaGEEEJICEFU5PcMOneAlXO7l4Z85yLojNGKfoq+vICXy9TOUQicLV6a9rjMRQghhMQlior8PkDeO/lefi9y+nNTfoheyv8De1JpG7XY2F8AAAAASUVORK5CYII=
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - charts.nextlinux.io
          resources:
          - nextlinuxengines
          - nextlinuxengines/status
          - nextlinuxengines/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          - persistentvolumeclaims
          - secrets
          - services
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - '*'
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - '*'
        serviceAccountName: nextlinux-engine-controller-manager
      deployments:
      - name: nextlinux-engine-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-addr=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=nextlinux-engine
                env:
                - name: RELATED_IMAGE_NEXTLINUX_ENGINE
                  value: registry.connect.redhat.com/nextlinux/engine0:v0.10.0-r0
                - name: RELATED_IMAGE_NEXTLINUX_POSTGRESQL
                  value: registry.redhat.io/rhel8/postgresql-96:latest
                image: registry.connect.redhat.com/nextlinux/engine-operator:v1.0.0
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 100m
                    memory: 90Mi
                  requests:
                    cpu: 100m
                    memory: 60Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: nextlinux-engine-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
        serviceAccountName: nextlinux-engine-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - analysis
  - docker
  - nextlinux
  - nextlinux-engine
  - image
  - security
  - vulnerability
  - scanner
  links:
  - name: Nextlinux Inc.
    url: https://www.nextlinux.com
  - name: Nextlinux Engine
    url: https://github.com/nextlinux/nextlinux-engine
  maintainers:
  - email: bradyt@nextlinux.com
    name: Brady Todhunter
  - email: zach@nextlinux.com
    name: Zach Hill
  maturity: alpha
  provider:
    name: Nextlinux Inc.
  version: 1.0.0
